/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sem */

#ifndef _Included_sem
#define _Included_sem
#ifdef __cplusplus
extern "C" {
#endif
#undef sem_MAX_SIZE
#define sem_MAX_SIZE 1024L
/*
 * Class:     sem
 * Method:    initShrSem
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_sem_initShrSem
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     sem
 * Method:    sendMsg
 * Signature: (IILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_sem_sendMsg
  (JNIEnv *, jobject, jint, jint, jobject, jint);

/*
 * Class:     sem
 * Method:    getMsg
 * Signature: (IILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_sem_getMsg
  (JNIEnv *, jobject, jint, jint, jobject, jint);

/*
 * Class:     sem
 * Method:    closeShm
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_sem_closeShm
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
