/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LinuxNIPC */

#ifndef _Included_LinuxNIPC
#define _Included_LinuxNIPC
#ifdef __cplusplus
extern "C" {
#endif
#undef LinuxNIPC_IPC_CREAT
#define LinuxNIPC_IPC_CREAT 512L
#undef LinuxNIPC_IPC_EXCL
#define LinuxNIPC_IPC_EXCL 1024L
#undef LinuxNIPC_IPC_NOWAIT
#define LinuxNIPC_IPC_NOWAIT 2048L
#undef LinuxNIPC_MSG_NOERROR
#define LinuxNIPC_MSG_NOERROR 4096L
#undef LinuxNIPC_MSG_EXCEPT
#define LinuxNIPC_MSG_EXCEPT 8192L
#undef LinuxNIPC_IPC_RMID
#define LinuxNIPC_IPC_RMID 0L
#undef LinuxNIPC_IPC_SET
#define LinuxNIPC_IPC_SET 1L
#undef LinuxNIPC_IPC_STAT
#define LinuxNIPC_IPC_STAT 2L
#undef LinuxNIPC_SHM_RDONLY
#define LinuxNIPC_SHM_RDONLY 4096L
#undef LinuxNIPC_SHM_RND
#define LinuxNIPC_SHM_RND 8192L
#undef LinuxNIPC_EAGAIN
#define LinuxNIPC_EAGAIN 11L
/*
 * Class:     LinuxNIPC
 * Method:    mkfifo
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_LinuxNIPC_mkfifo
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     LinuxNIPC
 * Method:    strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LinuxNIPC_strerror
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
