/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LinuxNIPC */

#ifndef _Included_LinuxNIPC
#define _Included_LinuxNIPC
#ifdef __cplusplus
extern "C" {
#endif
#undef LinuxNIPC_IPC_CREAT
#define LinuxNIPC_IPC_CREAT 512L
#undef LinuxNIPC_IPC_EXCL
#define LinuxNIPC_IPC_EXCL 1024L
#undef LinuxNIPC_IPC_NOWAIT
#define LinuxNIPC_IPC_NOWAIT 2048L
#undef LinuxNIPC_MSG_NOERROR
#define LinuxNIPC_MSG_NOERROR 4096L
#undef LinuxNIPC_MSG_EXCEPT
#define LinuxNIPC_MSG_EXCEPT 8192L
#undef LinuxNIPC_IPC_RMID
#define LinuxNIPC_IPC_RMID 0L
#undef LinuxNIPC_IPC_SET
#define LinuxNIPC_IPC_SET 1L
#undef LinuxNIPC_IPC_STAT
#define LinuxNIPC_IPC_STAT 2L
#undef LinuxNIPC_SHM_RDONLY
#define LinuxNIPC_SHM_RDONLY 4096L
#undef LinuxNIPC_SHM_RND
#define LinuxNIPC_SHM_RND 8192L
#undef LinuxNIPC_EAGAIN
#define LinuxNIPC_EAGAIN 11L
/*
 * Class:     LinuxNIPC
 * Method:    mkfifo
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_LinuxNIPC_mkfifo
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     LinuxNIPC
 * Method:    ftok
 * Signature: (Ljava/lang/String;C)I
 */
JNIEXPORT jint JNICALL Java_LinuxNIPC_ftok
  (JNIEnv *, jobject, jstring, jchar);

/*
 * Class:     LinuxNIPC
 * Method:    msgget
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_LinuxNIPC_msgget
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     LinuxNIPC
 * Method:    msgsnd
 * Signature: (ILjava/nio/ByteBuffer;III)I
 */
JNIEXPORT jint JNICALL Java_LinuxNIPC_msgsnd
  (JNIEnv *, jobject, jint, jobject, jint, jint, jint);

/*
 * Class:     LinuxNIPC
 * Method:    msgrcv
 * Signature: (ILjava/nio/ByteBuffer;III)I
 */
JNIEXPORT jint JNICALL Java_LinuxNIPC_msgrcv
  (JNIEnv *, jobject, jint, jobject, jint, jint, jint);

/*
 * Class:     LinuxNIPC
 * Method:    msgRmid
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_LinuxNIPC_msgRmid
  (JNIEnv *, jobject, jint);

/*
 * Class:     LinuxNIPC
 * Method:    initShrSem
 * Signature: (IILjava/lang/Boolean;)V
 */
JNIEXPORT void JNICALL Java_LinuxNIPC_initShrSem
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     LinuxNIPC
 * Method:    sendMsg
 * Signature: (IILjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_LinuxNIPC_sendMsg
  (JNIEnv *, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     LinuxNIPC
 * Method:    getMsg
 * Signature: (IILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_LinuxNIPC_getMsg
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     LinuxNIPC
 * Method:    close
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_LinuxNIPC_close
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     LinuxNIPC
 * Method:    strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LinuxNIPC_strerror
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
